import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../services/api_service.dart';

/// Briefing Screen - Daily AI Briefing
/// Morning briefing generated by the cortex
/// Solar Punk Tactical Theme
class BriefingScreen extends ConsumerStatefulWidget {
  const BriefingScreen({super.key});

  @override
  ConsumerState<BriefingScreen> createState() => _BriefingScreenState();
}

class _BriefingScreenState extends ConsumerState<BriefingScreen> {
  bool _isLoading = true;
  String? _error;

  // Data from APIs
  List<Map<String, dynamic>> _recentActivity = [];
  List<Map<String, dynamic>> _priorityTasks = [];
  int _totalTasksCount = 0;

  @override
  void initState() {
    super.initState();
    _loadBriefingData();
  }

  Future<void> _loadBriefingData() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      // Fetch activity feed and tasks in parallel
      final results = await Future.wait([
        ApiService.getActivity(limit: 5),
        ApiService.listTasks(limit: 5),
      ]);

      setState(() {
        // Parse activity feed
        final activityData = results[0] as Map<String, dynamic>;
        _recentActivity = (activityData['items'] ?? activityData['activities'] ?? [])
            .cast<Map<String, dynamic>>()
            .toList();

        // Parse tasks
        final tasksData = results[1] as Map<String, dynamic>;
        final allTasks = (tasksData['items'] ?? tasksData['tasks'] ?? [])
            .cast<Map<String, dynamic>>()
            .toList();

        // Filter priority tasks (high or urgent priority)
        _priorityTasks = allTasks
            .where((task) {
              final priority = task['priority']?.toString().toLowerCase() ?? '';
              return priority == 'high' || priority == 'urgent';
            })
            .toList();

        // If no high priority tasks, take first 3
        if (_priorityTasks.isEmpty) {
          _priorityTasks = allTasks.take(3).toList();
        }

        _totalTasksCount = tasksData['total'] ?? tasksData['pagination']?['total'] ?? allTasks.length;

        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    final bg = isDark ? const Color(0xFF0A0F0A) : const Color(0xFFF5F7F5);
    final cardBg = isDark ? const Color(0xFF0F1A0F) : Colors.white;
    final borderColor = isDark ? const Color(0xFF1A2F1A) : const Color(0xFFD5E5D5);
    final accentGreen = const Color(0xFF4ADE80);
    final accentOrange = const Color(0xFFF97316);
    final accentBlue = const Color(0xFF3B82F6);
    final accentPurple = const Color(0xFF8B5CF6);
    final textColor = isDark ? const Color(0xFFD1E5D1) : const Color(0xFF1A3A1A);
    final mutedText = isDark ? const Color(0xFF6B8F6B) : const Color(0xFF4A6B4A);

    final now = DateTime.now();
    final dateStr = DateFormat('EEEE, MMMM d, yyyy').format(now);

    return Scaffold(
      backgroundColor: bg,
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Container(
              padding: const EdgeInsets.fromLTRB(20, 16, 20, 20),
              decoration: BoxDecoration(
                color: cardBg,
                border: Border(bottom: BorderSide(color: borderColor)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          gradient: LinearGradient(colors: [accentPurple, const Color(0xFF6D28D9)]),
                          borderRadius: BorderRadius.circular(10),
                          boxShadow: [BoxShadow(color: accentPurple.withValues(alpha: 0.3), blurRadius: 8, offset: const Offset(0, 2))],
                        ),
                        child: const Icon(Icons.lightbulb, color: Colors.white, size: 22),
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Daily Briefing', style: TextStyle(color: textColor, fontSize: 22, fontWeight: FontWeight.w800)),
                            Text(dateStr, style: TextStyle(color: mutedText, fontSize: 12)),
                          ],
                        ),
                      ),
                      FilledButton.icon(
                        onPressed: _isLoading ? null : _loadBriefingData,
                        style: FilledButton.styleFrom(backgroundColor: accentGreen, foregroundColor: Colors.black),
                        icon: _isLoading
                            ? SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black))
                            : const Icon(Icons.refresh, size: 18),
                        label: Text(_isLoading ? 'Loading...' : 'Refresh'),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            // Briefing Content
            _isLoading
                ? Center(
                    child: Padding(
                      padding: const EdgeInsets.all(40),
                      child: Column(
                        children: [
                          CircularProgressIndicator(color: accentGreen),
                          const SizedBox(height: 16),
                          Text('Loading briefing...', style: TextStyle(color: mutedText)),
                        ],
                      ),
                    ),
                  )
                : _error != null
                    ? Center(
                        child: Padding(
                          padding: const EdgeInsets.all(40),
                          child: Column(
                            children: [
                              Icon(Icons.error_outline, size: 64, color: accentOrange),
                              const SizedBox(height: 16),
                              Text('Error loading briefing', style: TextStyle(color: textColor, fontSize: 16, fontWeight: FontWeight.w600)),
                              const SizedBox(height: 8),
                              Text(_error!, style: TextStyle(color: mutedText, fontSize: 12)),
                              const SizedBox(height: 16),
                              ElevatedButton.icon(
                                onPressed: _loadBriefingData,
                                icon: const Icon(Icons.refresh),
                                label: const Text('Retry'),
                                style: ElevatedButton.styleFrom(backgroundColor: accentGreen),
                              ),
                            ],
                          ),
                        ),
                      )
                    : Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Summary Card
                  _briefingCard(
                    'Good Morning',
                    'Here\'s your briefing for today. You have $_totalTasksCount tasks pending${_priorityTasks.isNotEmpty ? ' with ${_priorityTasks.length} high priority' : ''}. Recent activity shows ${_recentActivity.length} new events.',
                    Icons.wb_sunny,
                    accentOrange,
                    cardBg, borderColor, textColor, mutedText,
                  ),
                  const SizedBox(height: 16),
                  // Weather
                  _sectionHeader('Weather Forecast', accentBlue),
                  const SizedBox(height: 12),
                  _weatherCard(cardBg, borderColor, accentBlue, textColor, mutedText),
                  const SizedBox(height: 20),
                  // Calendar
                  _sectionHeader('Today\'s Schedule', accentGreen),
                  const SizedBox(height: 12),
                  _calendarItem('9:00 AM', 'Team Standup', 'Video call with engineering team', accentGreen, cardBg, borderColor, textColor, mutedText),
                  _calendarItem('11:30 AM', 'Project Review', 'OneMind OS milestone check', accentBlue, cardBg, borderColor, textColor, mutedText),
                  _calendarItem('3:00 PM', 'Garden Inspection', 'Check greenhouse sensors', accentOrange, cardBg, borderColor, textColor, mutedText),
                  const SizedBox(height: 20),
                  // Tasks
                  _sectionHeader('Priority Tasks', accentOrange),
                  const SizedBox(height: 12),
                  if (_priorityTasks.isEmpty)
                    Container(
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: cardBg,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: borderColor),
                      ),
                      child: Center(
                        child: Text('No priority tasks', style: TextStyle(color: mutedText)),
                      ),
                    )
                  else
                    ..._priorityTasks.map((task) {
                      final title = task['title'] ?? task['name'] ?? 'Untitled task';
                      final priority = task['priority']?.toString().toLowerCase() ?? 'medium';
                      final completed = task['completed'] == true || task['status'] == 'completed';
                      final priorityColor = priority == 'high' || priority == 'urgent'
                          ? accentOrange
                          : priority == 'low'
                              ? accentBlue
                              : const Color(0xFFF59E0B);
                      return _taskItem(title, priority, completed, priorityColor, cardBg, borderColor, textColor, mutedText);
                    }),
                  const SizedBox(height: 20),
                  // System Status
                  _sectionHeader('System Status', accentPurple),
                  const SizedBox(height: 12),
                  _systemStatusCard(cardBg, borderColor, accentGreen, accentOrange, textColor, mutedText),
                  const SizedBox(height: 20),
                  // AI Insights
                  _sectionHeader('AI Insights', accentPurple),
                  const SizedBox(height: 12),
                  _insightCard(
                    'Garden Zone B needs attention',
                    'Soil moisture levels have dropped 15% in the last 24 hours. Consider scheduling irrigation.',
                    Icons.grass,
                    accentOrange,
                    cardBg, borderColor, textColor, mutedText,
                  ),
                  _insightCard(
                    'Solar production is optimal',
                    'Current output is 4.2kW, 12% above average for this time of day.',
                    Icons.solar_power,
                    accentGreen,
                    cardBg, borderColor, textColor, mutedText,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _sectionHeader(String title, Color color) {
    return Text(
      title.toUpperCase(),
      style: TextStyle(color: color, fontSize: 11, fontWeight: FontWeight.w800, letterSpacing: 1.5),
    );
  }

  Widget _briefingCard(String title, String content, IconData icon, Color color,
      Color cardBg, Color borderColor, Color textColor, Color mutedText) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: color.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(icon, color: color, size: 28),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: TextStyle(color: textColor, fontSize: 18, fontWeight: FontWeight.w700)),
                const SizedBox(height: 6),
                Text(content, style: TextStyle(color: mutedText, fontSize: 13, height: 1.5)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _weatherCard(Color cardBg, Color borderColor, Color color, Color textColor, Color mutedText) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: borderColor),
      ),
      child: Row(
        children: [
          Icon(Icons.wb_sunny, color: const Color(0xFFFBBF24), size: 48),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('72°F - Sunny', style: TextStyle(color: textColor, fontSize: 20, fontWeight: FontWeight.w700)),
                Text('High: 78°F • Low: 58°F', style: TextStyle(color: mutedText, fontSize: 12)),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Row(children: [Icon(Icons.water_drop, size: 14, color: color), const SizedBox(width: 4), Text('45%', style: TextStyle(color: textColor, fontSize: 12))]),
              const SizedBox(height: 4),
              Row(children: [Icon(Icons.air, size: 14, color: color), const SizedBox(width: 4), Text('8 mph', style: TextStyle(color: textColor, fontSize: 12))]),
            ],
          ),
        ],
      ),
    );
  }

  Widget _calendarItem(String time, String title, String subtitle, Color color,
      Color cardBg, Color borderColor, Color textColor, Color mutedText) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: borderColor),
      ),
      child: Row(
        children: [
          Container(width: 4, height: 40, decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(2))),
          const SizedBox(width: 14),
          SizedBox(width: 70, child: Text(time, style: TextStyle(color: color, fontSize: 12, fontWeight: FontWeight.w700))),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: TextStyle(color: textColor, fontSize: 14, fontWeight: FontWeight.w600)),
                Text(subtitle, style: TextStyle(color: mutedText, fontSize: 11)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _taskItem(String title, String priority, bool done, Color color,
      Color cardBg, Color borderColor, Color textColor, Color mutedText) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: borderColor),
      ),
      child: Row(
        children: [
          Icon(done ? Icons.check_circle : Icons.radio_button_unchecked, color: done ? const Color(0xFF4ADE80) : mutedText, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Text(title, style: TextStyle(
              color: done ? mutedText : textColor,
              fontSize: 13,
              fontWeight: FontWeight.w600,
              decoration: done ? TextDecoration.lineThrough : null,
            )),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
            decoration: BoxDecoration(color: color.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),
            child: Text(priority.toUpperCase(), style: TextStyle(color: color, fontSize: 9, fontWeight: FontWeight.w700)),
          ),
        ],
      ),
    );
  }

  Widget _systemStatusCard(Color cardBg, Color borderColor, Color green, Color orange, Color textColor, Color mutedText) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(color: cardBg, borderRadius: BorderRadius.circular(10), border: Border.all(color: borderColor)),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _statusItem('Agents', '8 online', green),
          _statusItem('Sensors', '18 active', green),
          _statusItem('Machines', '2 running', orange),
          _statusItem('Alerts', '1 warning', orange),
        ],
      ),
    );
  }

  Widget _statusItem(String label, String value, Color color) {
    return Column(
      children: [
        Text(value, style: TextStyle(color: color, fontSize: 14, fontWeight: FontWeight.w700)),
        const SizedBox(height: 2),
        Text(label, style: TextStyle(color: color.withValues(alpha: 0.7), fontSize: 10)),
      ],
    );
  }

  Widget _insightCard(String title, String content, IconData icon, Color color,
      Color cardBg, Color borderColor, Color textColor, Color mutedText) {
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(color: color.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),
            child: Icon(icon, color: color, size: 20),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: TextStyle(color: textColor, fontSize: 13, fontWeight: FontWeight.w600)),
                const SizedBox(height: 2),
                Text(content, style: TextStyle(color: mutedText, fontSize: 11)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
